version: "3.9"

services:
    backend:
        container_name: "backend"
        build: app/backend/
        volumes:
            - ./app/backend/srcs:/srcs
        networks:
            - network
        expose:
            - 3000
        restart: unless-stopped
    frontend:
        container_name: "frontend"
        build: app/frontend/
        volumes:
            - ./app/frontend/srcs:/development
        networks:
            - network
        expose:
            - 4000
        depends_on:
            - "backend"
        restart: unless-stopped

    reverse_proxy:
        container_name: reverse_proxy
        build: app/reverse_proxy/
        networks:
            - network
        depends_on:
            - "frontend"
            - "backend"
        ports:
            - "4242:4242"
        restart: unless-stopped

networks:
    network: {}
